### ISSUE TITLE
How can i import SAC as a package?

### ISSUE THREAD

**Issue by filod** [Unity-Technologies/Standard-Assets-Characters#1]
I simply create a `package.json` file in `./Assets/_Standard Assets/Characters` fold, and when import it from other project i got these error:
![image](https://user-images.githubusercontent.com/679897/50512185-b900ff80-0acb-11e9-9efc-142fd0b8258d.png)

Any suggestion?

**Comment by Kaegun** [comment]
I copied the entire contents of the Assets folder from the project into my Unity project's Assets folder. Not elegant, but it worked.

**Comment by willgoldstone** [comment]
Hi! This is actually not yet supported as we're still in beta. We totally intend for this to be a package in the future once it is more stable.

**Comment by interior-night** [comment]
@willgoldstone Is it stable enough now?
