### ISSUE TITLE
Missing "SettingsScope"

### ISSUE THREAD

**Issue by ohlawdie** [Unity-Technologies/Standard-Assets-Characters#2]
Hey Unity, I've just pulled these files from the repo here and put everything into a new 2018.3 project. 
I get this compile error and I am unable to load up the test scene. 

Library\PackageCache\com.unity.postprocessing@2.0.19\PostProcessing\Editor\Utils\GlobalSettings.cs(55,72): error CS0103: The name 'SettingsScope' does not exist in the current context

![sacerror](https://user-images.githubusercontent.com/30779615/50565458-fdbfad00-0cfc-11e9-93ef-cac24f941cbb.png)

I took a look at the file and it is has a #if UNITY_EDITOR directive...I am confused but I hope I've given enough context here to find a solution to the problem. Any guidance would be great, thanks!

**Comment by willgoldstone** [comment]
We're seeing a few errors like this from Package management please try removing the affected systems and re-adding them via Package manager window (uninstall, install) - yes I know this is the classic IT solution of switching it off and on again.

**Comment by Yaffa16** [comment]
I'm still getting this error in unity 2018.3 versions. Any workaround. 
I uninstalled and reinstalled the packages multiple times
