### ISSUE TITLE
Rename Editor namespace

### ISSUE THREAD

**Issue by Kaegun** [Unity-Technologies/Standard-Assets-Characters#3]
The Editor namespace causes conflicts with other projects and classes that inherit from UnityEditors.Editor. I re-namespaced all SAC Editors locally to StandardAssets.Editor to resolve it in my local projects.

**Comment by LukeLamothe** [comment]
Thanks, yeah, this was a mistake and should be corrected in the next update :)

**Comment by Kaegun** [comment]
Thanks Luke. Good to catch up with you again. ;)
