### ISSUE TITLE
"com.unity.probuilder": "4.0.0-preview.37" cannot be found

### ISSUE THREAD

**Issue by Kaegun** [Unity-Technologies/Standard-Assets-Characters#4]
I have not been able to find this package. The SAC has imported, and I'll check about getting it to work.

**Comment by willgoldstone** [comment]
Have you tried removing probuilder and reinstalling in Package Manager?

**Comment by Kaegun** [comment]
From Package Manager the latest available version is 3.0.9, I couldn't find it anywhere else to install it. :-)
