### ISSUE TITLE
Jittering & unexpected turnaround on moving platform

### ISSUE THREAD

**Issue by filod** [Unity-Technologies/Standard-Assets-Characters#6]
as you can see, only when **the platform is rotating** and **after release moving input**, the character automatically turn around to face platform's forward direction (last couple of frames in gif)
![mp-bug](https://user-images.githubusercontent.com/679897/53679924-8dd69e80-3d0e-11e9-8033-435ddb287d3d.gif)

Another problem is jittering when move down slope:
![mp-bug2](https://user-images.githubusercontent.com/679897/53680035-523cd400-3d10-11e9-9dc3-0c68a5955473.gif)

also found some other jittering cases, happens quite often but i can't reproduce them (happens even on flat plane)

**Comment by Neecko** [comment]
Jitter down slopes happens and and it also plays the sound effects as it goes down.

**Comment by LukeLamothe** [comment]
This has been addressed.
