### ISSUE TITLE
ThirdPersonInput.m_IsStrafing & OpenCharacterController.m_Velocity inaccessible

### ISSUE THREAD

**Issue by interior-night** [Unity-Technologies/Standard-Assets-Characters#7]
Making `ThirdPersonInput.m_IsStrafing` and `OpenCharacterController.m_Velocity` public would add to this package's ability to integrate with other assets.

**Comment by LukeLamothe** [comment]
There is currently no internal need for these (or other similar) private variables to be exposed, but there is nothing stopping any user from exposing them, either via a property accessor or by making them public for their own needs.
