### ISSUE TITLE
Package not available through the Package Manager.

### ISSUE THREAD

**Issue by interior-night** [Unity-Technologies/Standard-Assets-Characters#8]
It would be great to allow this preview package to work with the Package Manager's import from git feature. I believe all it might take is to move the package file to the root?

**Comment by LukeLamothe** [comment]
SAC is still in Beta and is not a full Unity Package yet.

**Comment by interior-night** [comment]
@LukeLamothe Cool but I don't quite understand the difference between the Input System being available as a preview through the Package Manager for a good year before it was released (83 active issues in GitHub) and this package being considered a beta not worthy of the Package Manager despite its zero GitHub issues.

Also, am I to assume this isn't the character controller mentioned at Unite Copenhagen? The one that would be "released very soon" to the public? I'd like to know if I've spent all this time building my gameplay code around something that will be left unreleased. Do you have a timeframe for when this might move out of beta and into preview? I'm using the latest beta of Unity, by the way. ;-)

**Comment by interior-night** [comment]
Also, not to labour the point, but isn't a beta test meant to involve _testing_? And then improving things? ie. making more than a bi-monthly commit to your GitHub? Generally, when you beta test, you seek beta testers and then you listen to their feedback. Where are you getting feedback from now? Internally? Clearly not from the associated Unity forum thread! And yet despite the zero GitHub issues that feedback is holding you off from placing this in preview and putting it in the package manager? A bit more info from your end would reassure me that this is package is not dead. :-)
