### ISSUE TITLE
100+ "never assigned to" warnings.

### ISSUE THREAD

**Issue by interior-night** [Unity-Technologies/Standard-Assets-Characters#9]
When I import this package I get over 100 warnings in the console, regarding variables never assigned to. Is there a way to fix this?

**Comment by LukeLamothe** [comment]
These are all due to SerializedField variables that suffer from how Unity handles them:

https://issuetracker.unity3d.com/issues/serializedfield-fields-produce-field-is-never-assigned-to-dot-dot-dot-warning
